### ISSUE TITLE
Where can I found ISTD/UCF shadow detection dataset?

### ISSUE THREAD

**Issue by Mhaiyang** [wuzhe71/CPD#10]
Hi, Zhe Wu. Could you tell me where can I found ISTD/UCF shadow detection dataset? or could you send them to my email: taylormei@163.com. Thanks!

**Comment by wuzhe71** [comment]
@Mhaiyang ISTD dataset is available at `https://github.com/DeepInsight-PCALab/ST-CGAN`, and UCF dataset is available at `http://aqua.cs.uiuc.edu/site/projects/shadow.html`.

**Comment by jeya-maria-jose** [comment]
The UCF dataset link is not working ? Can someone please provide an working link ?

**Comment by intendto** [comment]
The UCF dataset link is not working ? Can someone please provide an working link ?

**Comment by helloyongyang** [comment]
The UCF dataset link is not working ? Can someone please provide an working link or provide a cloud disk link?

**Comment by GuLicheng** [comment]
The UCF dataset link is not working ? Can someone please provide an working link or provide a cloud disk link?

**Comment by GuLicheng** [comment]
The UCF dataset link is not working ? Can someone please provide an working link or provide a cloud disk link?

**Comment by fjyfly** [comment]
I also need the UCF shadow dataset. Could someone provide me with a working link?  The email is fengjunyingfly@gmail.com. Thanks a lot
