### ISSUE TITLE
Is the backbone of your CPD-ResNet model trained from scratch?

### ISSUE THREAD

**Issue by ysyscool** [wuzhe71/CPD#11]
I find that your ResNet.py doesn't have the _initialize_weights function as your vgg.py.

**Comment by wuzhe71** [comment]
@ysyscool The initialization is in CPD_ResNet_models.py.

**Comment by ysyscool** [comment]
> @ysyscool The initialization is in CPD_ResNet_models.py.

OK, I see it. Thanks for your reply.
