### ISSUE TITLE
Figure 2

### ISSUE THREAD

**Issue by clelouch** [wuzhe71/CPD#16]
Hi, thanks for your paper and code.
I am curious about how you generate the Figure 2. Your paper states that the saliency maps are genrated by using VGG16. However, feature maps in VGG16 have more than one channel. I guess the saliency maps are produced by correspongding side output layer in DSS, am i right?

**Comment by clelouch** [comment]
@wuzhe71

**Comment by wuzhe71** [comment]
@clelouch Square and sum maps along the channel. You can refer to the paper "Paying More Attention to Attention: Improving the Performance of Convolutional Neural Networks via Attention Transfer"

**Comment by clelouch** [comment]
Thanks for your help!
