### ISSUE TITLE
关于代码中的`ReLU`

### ISSUE THREAD

**Issue by ghost** [wuzhe71/CPD#3]
https://github.com/wuzhe71/CPD/blob/0d58898ab710d63d9cc103dd0997e026b8a7844e/model/CPD_ResNet_models.py#L21

请问这里的ReLU操作是刻意没写还是说是漏掉了？

谢谢您的工作。

**Comment by wuzhe71** [comment]
@LarT2P 我没有在decoder里加ReLU

**Comment by ghost** [comment]
> @LarT2P 我没有在decoder里加ReLU

这样做是有什么考量么?

**Comment by wuzhe71** [comment]
> > @LarT2P 我没有在decoder里加ReLU
> 
> 这样做是有什么考量么?

做实验时 感觉加不加区别不大

**Comment by ghost** [comment]
好的，感谢，很棒的工作！
