### ISSUE TITLE
我运行train.py报错

### ISSUE THREAD

**Issue by silencedog** [wuzhe71/CPD#4]
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from model.CPD_models import CPD_VGG
ImportError: bad magic number in 'model': b'\x03\xf3\r\n'
可有解决方法？

**Comment by wuzhe71** [comment]
> Traceback (most recent call last):
> File "train.py", line 9, in 
> from model.CPD_models import CPD_VGG
> ImportError: bad magic number in 'model': b'\x03\xf3\r\n'
> 可有解决方法？

把__init__.pyc 换成__init__.py再试试
