### ISSUE TITLE
The parameter of 'trainset'

### ISSUE THREAD

**Issue by Diamond101010** [wuzhe71/CPD#5]
train.py

```
parser = argparse.ArgumentParser()
parser.add_argument('--epoch', type=int, default=100, help='epoch number')
parser.add_argument('--lr', type=float, default=1e-4, help='learning rate')
parser.add_argument('--batchsize', type=int, default=10, help='training batch size')
parser.add_argument('--trainsize', type=int, default=352, help='training dataset size')
parser.add_argument('--clip', type=float, default=0.5, help='gradient clipping margin')
parser.add_argument('--is_ResNet', type=bool, default=False, help='VGG or ResNet backbone')
parser.add_argument('--decay_rate', type=float, default=0.1, help='decay rate of learning rate')
parser.add_argument('--decay_epoch', type=int, default=50, help='every n epochs decay learning rate')
opt = parser.parse_args()

print('Learning Rate: {} ResNet: {} Trainset: {}'.format(opt.lr, opt.is_ResNet, opt.trainset))
```

as you can see from above code , there no declaration about  'trainset' in add_argument(). However, this argument  be used in print (...., opt.trainset) 

what's mean of trainset? thank you for your anwser

**Comment by jjb202** [comment]
same question

**Comment by wuzhe71** [comment]
@Diamond101010 @suzhipeng It is a little fault. We use the training set of DUTS in the paper.  You can delete this line and run the code with setting the dataset path.

**Comment by suzhipeng** [comment]
Can you provide DUTS data sets?

**Comment by jjb202** [comment]
> @Diamond101010 @suzhipeng It is a little fault. We use the training set of DUTS in the paper. You can delete this line and run the code with setting the dataset path.

Can you provide DUTS data sets?

**Comment by wuzhe71** [comment]
@suzhipeng  http://saliencydetection.net/duts/

**Comment by Diamond101010** [comment]
> @Diamond101010 @suzhipeng It is a little fault. We use the training set of DUTS in the paper. You can delete this line and run the code with setting the dataset path.

I see, thank you for your anwser
