### ISSUE TITLE
About PiCANet performance at PSACAL-S 

### ISSUE THREAD

**Issue by suruoxi** [wuzhe71/CPD#8]
I notice that ,    PiCANet-R  performance in original paper is different of that in CPD paper.

PiCANet paper
FMeausre:    0.881
MAE:   0.087

CPD paper
FMeasure:   0.863
MAE:  0.075

Do you reimplement PiCANet or evaluate the provided saliency maps ?

**Comment by wuzhe71** [comment]
@suruoxi This is because that the PASCAL-S dataset provides two different ground truth: binary maps, and non-binary maps. Binary maps are widely used to evaluate traditional saliency models. Non binary maps are usually used to evaluate saliency ranking models.  The majority papers use binary maps.

**Comment by suruoxi** [comment]
Thanks for your comments.
